In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('tips.csv')

In [ ]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
movies_df=pd.read_csv("movies.csv",index_col="title")

In [ ]:
movies_df

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count,cast,crew,director
title,,,,,,,,,,,,,,,,,,,,,
Avatar,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
Pirates of the Caribbean: At World's End,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
Spectre,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
The Dark Knight Rises,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
John Carter,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
El Mariachi,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
Newlyweds,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
"Signed, Sealed, Delivered",4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
Shanghai Calling,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
My Date with Drew,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [ ]:
movies_df.head(10)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count,cast,crew,director
title,,,,,,,,,,,,,,,,,,,,,
Avatar,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
Pirates of the Caribbean: At World's End,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
Spectre,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
The Dark Knight Rises,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
John Carter,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
Spider-Man 3,5,258000000,Fantasy Action Adventure,http://www.sonypictures.com/movies/spider-man3/,559,dual identity amnesia sandstorm love of one's ...,en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,...,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,5.9,3576,Tobey Maguire Kirsten Dunst James Franco Thoma...,"[{'name': 'Francine Maisler', 'gender': 1, 'de...",Sam Raimi
Tangled,6,260000000,Animation Family,http://disney.go.com/disneypictures/tangled/,38757,hostage magic horse fairy tale musical,en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,...,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,7.4,3330,Zachary Levi Mandy Moore Donna Murphy Ron Perl...,"[{'name': 'John Lasseter', 'gender': 2, 'depar...",Byron Howard
Avengers: Age of Ultron,7,280000000,Action Adventure Science Fiction,http://marvel.com/movies/movie/193/avengers_ag...,99861,marvel comic sequel superhero based on comic b...,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,...,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,7.3,6767,Robert Downey Jr. Chris Hemsworth Mark Ruffalo...,"[{'name': 'Danny Elfman', 'gender': 2, 'depart...",Joss Whedon
Harry Potter and the Half-Blood Prince,8,250000000,Adventure Fantasy Family,http://harrypotter.warnerbros.com/harrypottera...,767,witch magic broom school of witchcraft wizardry,en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,...,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,7.4,5293,Daniel Radcliffe Rupert Grint Emma Watson Tom ...,"[{'name': 'Bruno Delbonnel', 'gender': 0, 'dep...",David Yates
Batman v Superman: Dawn of Justice,9,250000000,Action Adventure Fantasy,http://www.batmanvsupermandawnofjustice.com/,209112,dc comics vigilante superhero based on comic b...,en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,...,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,5.7,7004,Ben Affleck Henry Cavill Gal Gadot Amy Adams J...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Zack Snyder

In [ ]:
movies_df.tail(2)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count,cast,crew,director
title,,,,,,,,,,,,,,,,,,,,,
Shanghai Calling,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
My Date with Drew,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [ ]:
movies_df.shape
movies_df.describe()

,index,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4803.000000,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2401.000000,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,1386.651002,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,1200.500000,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,2401.000000,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,3601.500000,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,4802.000000,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [ ]:
movies_df=movies_df.drop_duplicates()
movies_df.shape

(4803, 23)

In [ ]:
import pandas as pd
d={'one':pd.Series([1,2,3],index=['a','b','c']),
   'two':pd.Series([1,2,3,4],index=['a','b','c','d'])
  }
df=pd.DataFrame(d)
print("Adding a new column by passing as Series:")
df['three']=pd.Series([10,20,30],index=['a','b','c'])
print(df)
print("Adding a new column using the existing columns in DataFrame:")
df['four']=df['one']+df['three']
print(df)

Adding a new column by passing as Series:
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
Adding a new column using the existing columns in DataFrame:
   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN

In [ ]:
import pandas as pd
d={'one':pd.Series([1,2,3],index=['a','b','c']),
   'two':pd.Series([1,2,3,4],index=['a','b','c','d'])
  }
df=pd.DataFrame(d)
print("Our dataframe is:")
print(df)
print("Deleting the first column using DEL function:")
del df['one']
print(df)
print("Deleting another column using POP function:")
df.pop('two')
print(df)
print(df[1:4])

Our dataframe is:
   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4
Deleting the first column using DEL function:
   two
a    1
b    2
c    3
d    4
Deleting another column using POP function:
Empty DataFrame
Columns: []
Index: [a, b, c, d]
Empty DataFrame
Columns: []
Index: [b, c, d]

In [ ]:
import pandas as pd
d={'one':pd.Series([1,2,3],index=['a','b','c']),
   'two':pd.Series([1,2,3,4],index=['a','b','c','d'])
  }
df=pd.DataFrame(d)
print(df[3:4])

   one  two
d  NaN    4

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    "A":[1,5,3,4,2],
    "B":[3,2,4,3,4],
    "C":[2,2,7,3,4],
    "D":[4,3,6,12,7]
}, index=["A1","A2","A3","A4","A5"])

df2 = pd.DataFrame({
    "A":[1,5,3,4,2],
    "B":[3,2,4,3,4],
    "C":[2,2,7,3,4],
    "D":[4,3,6,12,7]
}, index=["A1","A2","A3","A4","A5"])

print(df1.reindex_like(df2))

    A  B  C   D
A1  1  3  2   4
A2  5  2  2   3
A3  3  4  7   6
A4  4  3  3  12
A5  2  4  4   7

In [ ]:
import pandas as pd
df=pd.read_csv("movies.csv")
total_nans=df.isna().sum().sum()
nans_per_columns=df.isna().sum()
print("Total Nans:",total_nans)
print("NANS per column:",nans_per_columns)

Total Nans: 4454
NANS per column: index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [ ]:
df.dropna()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4772,4772,31192,Drama Action Comedy,http://downterrace.blogspot.com/,42151,murder dark comedy crime family,en,Down Terrace,After serving jail time for a mysterious crime...,1.330379,...,89.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You're only as good as the people you know.,Down Terrace,6.3,26,Robert Hill Robin Hill Julia Deakin David Scha...,"[{'name': 'Ben Wheatley', 'gender': 2, 'depart...",Ben Wheatley
4773,4773,27000,Comedy,http://www.miramax.com/movie/clerks/,2292,salesclerk loser aftercreditsstinger,en,Clerks,Convenience and video store clerks Dante and R...,19.748658,...,92.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Just because they serve you doesn't mean they ...,Clerks,7.4,755,Brian O'Halloran Jeff Anderson Jason Mewes Kev...,"[{'name': 'Kevin Smith', 'gender': 2, 'departm...",Kevin Smith
4781,4781,22000,Comedy Romance,https://www.facebook.com/DrySpellMovie,255266,dating divorce sex scene sex comedy anti roman...,en,Dry Spell,Sasha tries to get her soon-to-be ex husband K...,0.048948,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Getting divorced does funny things to a girl,Dry Spell,6.0,1,Suzi Lorraine Jared Degado Heather Dorff Racha...,"[{'name': 'Travis Legge', 'gender': 0, 'depart...",Travis Legge
4791,4791,13,Horror,http://tincanmanthemovie.com/,157185,home invasion,en,Tin Can Man,Recently dumped by his girlfirend for another ...,0.332679,...,84.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Everything You've Heard is True,Tin Can Man,2.0,1,Michael Parle Emma Eliza Regan Patrick O'Donne...,"[{'name': 'Ivan Kavanagh', 'gender': 0, 'depar...",Ivan Kavanagh
4796,4796,7000,Science Fiction Drama Thriller,http://www.primermovie.com,14337,distrust garage identity crisis time travel ti...,en,Primer,Friends/fledgling entrepreneurs invent a devic...,23.307949,...,77.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,What happens if it actually works?,Primer,6.9,658,Shane Carruth David Sullivan Casey Gooden Anan...,"[{'name': 'Shane Carruth', 'gender': 2, 'depar...",Shane Carruth

In [ ]:
df.dropna(axis=1)

,index,budget,id,original_language,original_title,popularity,production_companies,production_countries,revenue,spoken_languages,status,title,vote_average,vote_count,crew
0,0,237000000,19995,en,Avatar,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2787965087,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Avatar,7.2,11800,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd..."
1,1,300000000,285,en,Pirates of the Caribbean: At World's End,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",961000000,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Pirates of the Caribbean: At World's End,6.9,4500,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa..."
2,2,245000000,206647,en,Spectre,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",880674609,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,Spectre,6.3,4466,"[{'name': 'Thomas Newman', 'gender': 2, 'depar..."
3,3,250000000,49026,en,The Dark Knight Rises,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1084939099,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Dark Knight Rises,7.6,9106,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm..."
4,4,260000000,49529,en,John Carter,43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",284139100,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,John Carter,6.1,2124,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,9367,es,El Mariachi,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",2040920,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,El Mariachi,6.6,238,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de..."
4799,4799,9000,72766,en,Newlyweds,0.642552,[],[],0,[],Released,Newlyweds,5.9,5,"[{'name': 'Edward Burns', 'gender': 2, 'depart..."
4800,4800,0,231617,en,"Signed, Sealed, Delivered",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Signed, Sealed, Delivered",7.0,6,"[{'name': 'Carla Hetland', 'gender': 0, 'depar..."
4801,4801,0,126186,en,Shanghai Calling,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Shanghai Calling,5.7,7,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm..."
4802,4802,0,25975,en,My Date with Drew,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,My Date with Drew,6.3,16,"[{'name': 'Clark Peterson', 'gender': 2, 'depa..."

In [ ]:
df.shape

(4803, 24)

In [ ]:
df.fillna(0)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,0,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,0,72766,0,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,0,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,0,http://shanghaicalling.com/,126186,0,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,0,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,0,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame({
    'budget':[1000,2000,np.nan,10,1000]
})
df['budget'].fillna(df['budget'].mode()[0],inplace=True)
print(df)

   budget
0  1000.0
1  2000.0
2  1000.0
3    10.0
4  1000.0

/tmp/ipykernel_908/3404163119.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['budget'].fillna(df['budget'].mode()[0],inplace=True)

In [ ]:
df_ffill=df.copy()
df_ffill.fillna(method='ffill',inplace=True)
print(df_ffill)

   budget
0  1000.0
1  2000.0
2  1000.0
3    10.0
4  1000.0

/tmp/ipykernel_908/594003542.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill.fillna(method='ffill',inplace=True)

In [ ]:
df_bfill=df.copy()
df_bfill.fillna(method='bfill',inplace=True)
print(df_bfill)

   budget
0  1000.0
1  2000.0
2  1000.0
3    10.0
4  1000.0

/tmp/ipykernel_908/340482599.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill.fillna(method='bfill',inplace=True)

In [ ]:
import pandas as pd

# Sample dataset with inconsistent date formats
df = pd.DataFrame({
    'Date': ['2025-01-05', '05/01/2025', 'Jan 5, 2025', '2025.01.05']
})

# Convert all dates to standard ISO format (YYYY-MM-DD)
df['Date'] = pd.to_datetime(df['Date'], errors='coerce').dt.strftime('%Y-%m-%d')

print(df)

         Date
0  2025-01-05
1         NaN
2         NaN
3         NaN

In [ ]:
df= pd.DataFrame({
    'Name': ['Alice', 'BOB', 'charlie', 'DAVID']
})

# Convert all names to lowercase
df['Name_lower'] = df['Name'].str.lower()
print(df)

# Convert all names to uppercase
df['Name_upper'] = df['Name'].str.upper()

print(df.head(10))

      Name Name_lower
0    Alice      alice
1      BOB        bob
2  charlie    charlie
3    DAVID      david
      Name Name_lower Name_upper
0    Alice      alice      ALICE
1      BOB        bob        BOB
2  charlie    charlie    CHARLIE
3    DAVID      david      DAVID

In [ ]:
df=pd.read_csv("movies.csv")
df['title_lower']=df['original_title'].str.lower()
print(df)
df['title_upper']=df['original_title'].str.upper()
print(df)

      index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction
1         1  300000000                  Adventure Fantasy Action
2         2  245000000                    Action Adventure Crime
3         3  250000000               Action Crime Drama Thriller
4         4  260000000          Action Adventure Science Fiction
...     ...        ...                                       ...
4798   4798     220000                     Action Crime Thriller
4799   4799       9000                            Comedy Romance
4800   4800          0             Comedy Drama Romance TV Movie
4801   4801          0                                       NaN
4802   4802          0                               Documentary

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995
1          http://disney.go.com/disneypictures/pirates/     285
2           http://www.sonypictures.com/movies/spectre/  206647
3                    http://www.thedarkknightrises.com/   49026
4                  http://movies.disney.com/john-carter   49529
...                                                 ...     ...
4798                                                NaN    9367
4799                                                NaN   72766
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617
4801                        http://shanghaicalling.com/  126186
4802                                                NaN   25975

                                               keywords original_language  \
0     culture clash future space war space colony so...                en
1     ocean drug abuse exotic island east india trad...                en
2            spy based on novel secret agent sequel mi6                en
3     dc comics crime fighter terrorist secret ident...                en
4     based on novel mars medallion space travel pri...                en
...                                                 ...               ...
4798  united states\u2013mexico barrier legs arms pa...                es
4799                                                NaN                en
4800  date love at first sight narration investigati...                en
4801                                                NaN                en
4802               obsession camcorder crush dream girl                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...
2     A cryptic message from Bond’s past sends him o...  107.376788  ...
3     Following the death of District Attorney Harve...  112.312950  ...
4     John Carter is a war-weary, former military ca...   43.926995  ...
...                                                 ...         ...  ...
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...
4802  Ever since the second grade when he first saw ...    1.929883  ...

                                       spoken_languages    status  \
0     [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1              [{"iso_639_1": "en", "name": "English"}]  Released
2     [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3              [{"iso_639_1": "en", "name": "English"}]  Released
4              [{"iso_639_1": "en", "name": "English"}]  Released
...                                                 ...       ...
4798      [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]  Released
4799                                                 []  Released
4800           [{"iso_639_1": "en", "name": "English"}]  Released
4801           [{"iso_639_1": "en", "name": "English"}]  Released
4802           [{"iso_639_1": "en", "name": "English"}]  Released

                                                tagline  \
0                           Enter the World of Pandora.
1        At the end of the world, the adventure begins.
2                                 A Plan No One Escapes
3                                       The Legend Ends
4                  Lost in our world, found in another.
...                                                 ...
4798  He didn't come looking for trouble, but troubl...
4799  A newlywed couple's honeymoon is upended by th...
4800                                                NaN
4801                           A New Yorker in Shanghai
4802                                                NaN

                                         title  vote_average vote_count  \
0                                       Avatar           7.2      11800
1     Pirates of the Caribbean: At World's End           6.9       4500
2                                      Spectre           6.3       4466
3                        The Dark Knight Rises           7.6       9106
4                                  John Carter           6.1       2124
...                                        ...           ...        ...
4798                               El Mariachi           6.6        238
4799                                 Newlyweds           5.9          5
4800                 Signed, Sealed, Delivered           7.0          6
4801                          Shanghai Calling           5.7          7
4802                         My Date with Drew           6.3         16

                                                   cast  \
0     Sam Worthington Zoe Saldana Sigourney Weaver S...
1     Johnny Depp Orlando Bloom Keira Knightley Stel...
2     Daniel Craig Christoph Waltz L\u00e9a Seydoux ...
3     Christian Bale Michael Caine Gary Oldman Anne ...
4     Taylor Kitsch Lynn Collins Samantha Morton Wil...
...                                                 ...
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...

                                                   crew           director  \
0     [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1     [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2     [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3     [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4     [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton
...                                                 ...                ...
4798  [{'name': 'Robert Rodriguez', 'gender': 0, 'de...   Robert Rodriguez
4799  [{'name': 'Edward Burns', 'gender': 2, 'depart...       Edward Burns
4800  [{'name': 'Carla Hetland', 'gender': 0, 'depar...        Scott Smith
4801  [{'name': 'Daniel Hsia', 'gender': 2, 'departm...        Daniel Hsia
4802  [{'name': 'Clark Peterson', 'gender': 2, 'depa...   Brian Herzlinger

                                   title_lower
0                                       avatar
1     pirates of the caribbean: at world's end
2                                      spectre
3                        the dark knight rises
4                                  john carter
...                                        ...
4798                               el mariachi
4799                                 newlyweds
4800                 signed, sealed, delivered
4801                          shanghai calling
4802                         my date with drew

[4803 rows x 25 columns]
      index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction
1         1  300000000                  Adventure Fantasy Action
2         2  245000000                    Action Adventure Crime
3         3  250000000               Action Crime Drama Thriller
4         4  260000000          Action Adventure Science Fiction
...     ...        ...                                       ...
4798   4798     220000                     Action Crime Thriller
4799   4799       9000                            Comedy Romance
4800   4800          0             Comedy Drama Romance TV Movie
4801   4801          0                                       NaN
4802   4802          0                               Documentary

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995
1          http://disney.go.com/disneypictures/pirates/     285
2           http://www.sonypictures.com/movies/spectre/  206647
3                    http://www.thedarkknightrises.com/   49026
4                  http://movies.disney.com/john-carter   49529
...                                                 ...     ...
4798                                                NaN    9367
4799                                                NaN   72766
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617
4801                        http://shanghaicalling.com/  126186
4802                                                NaN   25975

                                               keywords original_language  \
0     culture clash future space war space colony so...                en
1     ocean drug abuse exotic island east india trad...                en
2            spy based on novel secret agent sequel mi6                en
3     dc comics crime fighter terrorist secret ident...                en
4     based on novel mars medallion space travel pri...                en
...                                                 ...               ...
4798  united states\u2013mexico barrier legs arms pa...                es
4799                                                NaN                en
4800  date love at first sight narration investigati...                en
4801                                                NaN                en
4802               obsession camcorder crush dream girl                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...
2     A cryptic message from Bond’s past sends him o...  107.376788  ...
3     Following the death of District Attorney Harve...  112.312950  ...
4     John Carter is a war-weary, former military ca...   43.926995  ...
...                                                 ...         ...  ...
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...
4802  Ever since the second grade when he first saw ...    1.929883  ...

        status                                            tagline  \
0     Released                        Enter the World of Pandora.
1     Released     At the end of the world, the adventure begins.
2     Released                              A Plan No One Escapes
3     Released                                    The Legend Ends
4     Released               Lost in our world, found in another.
...        ...                                                ...
4798  Released  He didn't come looking for trouble, but troubl...
4799  Released  A newlywed couple's honeymoon is upended by th...
4800  Released                                                NaN
4801  Released                           A New Yorker in Shanghai
4802  Released                                                NaN

                                         title  vote_average  vote_count  \
0                                       Avatar           7.2       11800
1     Pirates of the Caribbean: At World's End           6.9        4500
2                                      Spectre           6.3        4466
3                        The Dark Knight Rises           7.6        9106
4                                  John Carter           6.1        2124
...                                        ...           ...         ...
4798                               El Mariachi           6.6         238
4799                                 Newlyweds           5.9           5
4800                 Signed, Sealed, Delivered           7.0           6
4801                          Shanghai Calling           5.7           7
4802                         My Date with Drew           6.3          16

                                                   cast  \
0     Sam Worthington Zoe Saldana Sigourney Weaver S...
1     Johnny Depp Orlando Bloom Keira Knightley Stel...
2     Daniel Craig Christoph Waltz L\u00e9a Seydoux ...
3     Christian Bale Michael Caine Gary Oldman Anne ...
4     Taylor Kitsch Lynn Collins Samantha Morton Wil...
...                                                 ...
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...

                                                   crew           director  \
0     [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1     [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2     [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3     [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4     [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton
...                                                 ...                ...
4798  [{'name': 'Robert Rodriguez', 'gender': 0, 'de...   Robert Rodriguez
4799  [{'name': 'Edward Burns', 'gender': 2, 'depart...       Edward Burns
4800  [{'name': 'Carla Hetland', 'gender': 0, 'depar...        Scott Smith
4801  [{'name': 'Daniel Hsia', 'gender': 2, 'departm...        Daniel Hsia
4802  [{'name': 'Clark Peterson', 'gender': 2, 'depa...   Brian Herzlinger

                                   title_lower  \
0                                       avatar
1     pirates of the caribbean: at world's end
2                                      spectre
3                        the dark knight rises
4                                  john carter
...                                        ...
4798                               el mariachi
4799                                 newlyweds
4800                 signed, sealed, delivered
4801                          shanghai calling
4802                         my date with drew

                                   title_upper
0                                       AVATAR
1     PIRATES OF THE CARIBBEAN: AT WORLD'S END
2                                      SPECTRE
3                        THE DARK KNIGHT RISES
4                                  JOHN CARTER
...                                        ...
4798                               EL MARIACHI
4799                                 NEWLYWEDS
4800                 SIGNED, SEALED, DELIVERED
4801                          SHANGHAI CALLING
4802                         MY DATE WITH DREW

[4803 rows x 26 columns]